version: "3"

services:
  web-api-db:
    image: postgres
    container_name: web-api-db-container
    environment:
      - POSTGRES_USER=timeseries_user
      - POSTGRES_PASSWORD=timeseries_password
      - POSTGRES_DB=timeseries_db

  nifi-db:
    build: ./timeseries_project/nifi/db
    container_name: nifi-db-container
    environment:
      - POSTGRES_DB=nifi_db
      - POSTGRES_USER=nifi_user
      - POSTGRES_PASSWORD=nifi_password

    ports:
      - 5432:5432 # Expose port 5432 to the host

  nifi-api:
    image: apache/nifi:latest
    command: bash -c "wget https://jdbc.postgresql.org/download/postgresql-42.5.4.jar /opt/nifi/nifi-current/lib"
    container_name: nifi-api-container
    expose:
      - 5000
    ports:
      - 8080:8080
    environment:
      - NIFI_WEB_HTTP_PORT=8080
    depends_on:
      - nifi-db

  web-api:
    build: ./timeseries_project
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    container_name: web-api-container
    volumes:
      - migrations:/timeseries_project/migrations
    ports:
      - 8001:8001
    depends_on:
      - web-api-db

volumes:
  migrations:
