## Configuration file for the time series simulator
## You can change the values of the parameters to generate different datasets
## But make sure that the parameters are valid
## The configuration can be extended to include more parameters and components
## Check the documentation for more details

# Time index parameters
# 1 Year of timeseries data with 1 minute sampling frequency
time_index: {
  start_date: "2019-01-01",
  end_date: "2023-01-01",
  sampling_frequency_in_minutes: 60 # 1 hour
}

# Main components parameters
multiplicative: False,
main_components: {
  trend: {
    coefficients: [0.05, 0.001] ,
  },
  # You can add more than one seasonality component
  seasonality: [
    {
      in_days: False,
      period: 24, # Daily
      amplitude: 0.5
    },
    {
      in_days: True,
      period: 365, # Yearly
      amplitude: 0.005
    }
  ] ,
}

# Residual components parameters
residual_components: {
  noise: {
    noise_level: 0.01
  },
  outliers: {
    outlier_ratio: 0.001
  },
}

# Number of generated datasets
n_datasets: 10
